name: Release-js
on:
  pull_request:
    branches:
      - main

defaults:
  run:
    working-directory: packages/js

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'
          # registry-url: 'https://registry.npmjs.org'
      # - run: npm version patch
      - run: npm ci
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

# jobs:
#   release-js:
#     name: Release
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout
#         uses: actions/checkout@v2
#         with:
#           fetch-depth: 0

#       - name: Setup Node.js
#         uses: actions/setup-node@v2
#         with:
#           node-version: 'lts/*'
#       - run: npm version patch
#       - run: npm ci && npm run build
#       - run: npm publish
#         env:
#           NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      # - name: update js version
      #   working-directory: packages/js
      #   run: npm version patch

      # - name: Install dependencies
      #   working-directory: packages/js
      #   run: npm ci && npm run build

      # - name: Release js
      #   run: npm publish
      #   working-directory: packages/js
      #   env:
      #     NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          