name: Release Java

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  release-java:
    runs-on: ubuntu-20.04
    defaults:
      run:
        working-directory: packages/java
    steps:
      - uses: actions/checkout@v2.3.4

      - name: Set up JDK 11 for running Gradle
        uses: actions/setup-java@v2
        with:
          distribution: adopt
          java-version: 11.0.11+9

      - name: Increment Patch Version
        run: ./gradlew incrementPatchVersion --dry-run

      - name: Publish package
        uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
        with:
          arguments: publish --dry-run
          gradle-executable: packages/java/
        env:
          MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.OSSRH_TOKEN }}
