name: Release-js
on:
  push:
    branches:
      - main

defaults:
  run:
    working-directory: packages/js

jobs:
  release-js:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'
          registry-url: 'https://registry.npmjs.org'
      - run: npm version patch
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Commit new version to package.json
      - run: npm ci
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
