name: Release-js
on:
  push:
    branches:
      - main

jobs:
  release-js:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 'lts/*'

      - name: update js version
        working-directory: packages/js
        run: npm version patch

      - name: Install dependencies
        working-directory: packages/js
        run: npm ci && npm run build

      - name: Release js
        run: npm publish --dry-run
        working-directory: packages/js
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          