name: Release-py
on:
  push:
    branches:
      - main

jobs:
  release-py:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: install poetry
        run: pip install poetry

      - name: update python version
        working-directory: packages/python
        run: poetry version patch

      - name: Release python
        working-directory: packages/python
        run: poetry publish --dry-run --build --username __token__ --password ${{ secrets.PYPI_TOKEN }}
        
        